# Generated by Django 5.2 on 2026-09-30 17:24

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('LIVE', 'Live'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], default='UPCOMING', max_length=10)),
                ('current_innings_state', models.JSONField(blank=True, default=dict, help_text='Live scoring state for the current innings (runs, wickets, overs, …).')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'matches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('jersey_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(999)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='players/images/')),
                ('role', models.CharField(choices=[('BAT', 'Batsman'), ('BOWL', 'Bowler'), ('AR', 'All-Rounder'), ('WK', 'Wicket Keeper')], default='BAT', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['team', 'jersey_number'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='teams/logos/')),
                ('theme_color', models.CharField(default='#000000', help_text='Hex colour code, e.g. #FF5733', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex colour (e.g. #1A2B3C).', regex='^#[0-9A-Fa-f]{6}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ball',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('innings', models.PositiveSmallIntegerField(default=1, help_text='Which innings this delivery belongs to (1-4).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('over', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('ball_number', models.PositiveSmallIntegerField(help_text='Ball number within the over (can exceed 6 with extras).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('runs', models.PositiveSmallIntegerField(default=0)),
                ('extras', models.PositiveSmallIntegerField(default=0)),
                ('extra_type', models.CharField(choices=[('NONE', 'None'), ('WIDE', 'Wide'), ('NO_BALL', 'No Ball'), ('BYE', 'Bye'), ('LB', 'Leg Bye'), ('PEN', 'Penalty')], default='NONE', max_length=7)),
                ('is_wicket', models.BooleanField(default=False)),
                ('wagon_angle', models.FloatField(blank=True, help_text='Shot angle in degrees (0-360) for wagon wheel.', null=True)),
                ('wagon_distance', models.FloatField(blank=True, help_text='Shot distance in metres for wagon wheel.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balls', to='scoring.match')),
                ('batsman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balls_faced', to='scoring.player')),
                ('bowler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balls_bowled', to='scoring.player')),
            ],
            options={
                'ordering': ['match', 'innings', 'over', 'ball_number'],
            },
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='scoring.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='batting_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_batting', to='scoring.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='bowling_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_bowling', to='scoring.team'),
        ),
        migrations.CreateModel(
            name='BowlingInnings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overs_bowled', models.DecimalField(decimal_places=1, default=0, help_text='Overs bowled (e.g. 4.3 means 4 overs and 3 balls).', max_digits=4)),
                ('runs_conceded', models.PositiveIntegerField(default=0)),
                ('wickets', models.PositiveIntegerField(default=0)),
                ('maidens', models.PositiveIntegerField(default=0)),
                ('wides', models.PositiveIntegerField(default=0)),
                ('no_balls', models.PositiveIntegerField(default=0)),
                ('innings_number', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowling_innings', to='scoring.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowling_innings', to='scoring.player')),
            ],
            options={
                'verbose_name_plural': 'bowling innings',
                'ordering': ['-created_at'],
                'unique_together': {('match', 'player', 'innings_number')},
            },
        ),
        migrations.CreateModel(
            name='BattingInnings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('runs_scored', models.PositiveIntegerField(default=0)),
                ('balls_faced', models.PositiveIntegerField(default=0)),
                ('fours', models.PositiveIntegerField(default=0)),
                ('sixes', models.PositiveIntegerField(default=0)),
                ('dismissal', models.CharField(choices=[('NOT_OUT', 'Not Out'), ('BOWLED', 'Bowled'), ('CAUGHT', 'Caught'), ('LBW', 'LBW'), ('RUN_OUT', 'Run Out'), ('STUMPED', 'Stumped'), ('HIT_WICKET', 'Hit Wicket'), ('RETIRED', 'Retired')], default='NOT_OUT', max_length=10)),
                ('innings_number', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batting_innings', to='scoring.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batting_innings', to='scoring.player')),
            ],
            options={
                'verbose_name_plural': 'batting innings',
                'ordering': ['-created_at'],
                'unique_together': {('match', 'player', 'innings_number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('team', 'jersey_number')},
        ),
    ]
