# Generated by Django 5.2 on 2026-10-03 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0002_alter_player_team'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player',
            unique_together=set(),
        ),
    ]
